### ISSUE TITLE
Insufficient training data or bad validation_split value

### ISSUE THREAD

**Issue by jmarcosfer** [GuitarML/SmartAmpPro#14]
I'm trying to train SmartAmpPro on a couple of 3min recordings for input and output, but I get the following error on the train.py script:

```
train.py:118: WavFileWarning: Chunk (non-data) not understood, skipping it.
  in_rate, stereo_data = wavfile.read(args.in_file)
train.py:45: RuntimeWarning: invalid value encountered in true_divide
  return data / data_norm

Training on split data 1/6
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    main(args)
  File "train.py", line 159, in main
    model.fit(X_random,y_random, epochs=epochs, batch_size=batch_size, validation_split=0.2)  
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1041, in fit
    (x, y, sample_weight), validation_split=validation_split))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1380, in train_validation_split
    batch_dim=batch_dim, validation_split=validation_split))
ValueError: Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.
```

What am I getting wrong?

Any pointers would be welcome, super excited to try this!

Thanks!

**Comment by GuitarML** [comment]
@jmarcosfer It looks like it wasn’t able to read data from your wav file, or it expected a stereo file and didnt find the output data. Are you using a single stereo wav recorded from SmartAmpPro or two separate wav files? If you are using the command line on the train.py script can you also share what you entered, or did you use the Train Tone button? 

Thanks!

**Comment by jmarcosfer** [comment]
I used the train.py script, because it was getting stuck on 15% using the Train Tone button.

```python train.py Input.wav Output.wav```
That's the command I used, so I guess that's the problem: two separate audio files instead of a single stereo one (which I understand is what it's supposed to be). These Input.wav and Output.wav files were not captured by SmartAmpPro, I recorded them on two separate tracks on Reaper.

I guess just merging these two files into a stereo file should work then? In that case, does it need to be interleaved?

thank you!

**Comment by GuitarML** [comment]
No need to merge them, it supports using two files, except the command would look like this:

python train.py input.wav model_name —out_file=out.wav

so the out file is an optional argument in the case of this script, let me know if that doesn’t fix it!

**Comment by jmarcosfer** [comment]
That worked! I realised I should have looked at the help (`python train.py --help` shows how to use it, for anyone lost)

Thank you!
